name: compile_deploy_latex
on: [push]
jobs:
  paper:
    runs-on: ubuntu-latest
    env:
      # Edit here with the names of your latex file and directory (can use ".")
      DIR: .
      FILE: IA
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Calibri
        run: sudo mkdir /usr/share/fonts/truetype/calibri/; sudo wget -O /usr/share/fonts/truetype/calibri/calibri.ttf https://github.com/jondot/dotfiles/blob/d52863730c3d0691781dc3d6cd4f418731e67071/.fonts/calibri.ttf?raw=true; sudo wget -O /usr/share/fonts/truetype/calibri/calibrii.ttf https://github.com/jondot/dotfiles/blob/d52863730c3d0691781dc3d6cd4f418731e67071/.fonts/calibrii.ttf?raw=true; sudo wget -O /usr/share/fonts/truetype/calibri/calibrib.ttf https://github.com/jondot/dotfiles/blob/d52863730c3d0691781dc3d6cd4f418731e67071/.fonts/calibrib.ttf?raw=true; fc-cache -fv
      - name: Install TeXlive
        run: sudo apt-get install texlive texlive-publishers texlive-science latexmk cm-super texlive-xetex texlive-extra-utils
      - name: LaTeX compile
        working-directory: ${{ env.DIR }}
        run: latexmk -xelatex -interaction=nonstopmode -enable-write18 -file-line-error ${{ env.FILE }}
      - name: Move file
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts
  
  deploy:
    # Edit here if compiling multiple papers
    needs: [paper]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          path: ./github_artifacts
      - name: Move
        run: mkdir -p github_deploy && mv github_artifacts/*/* .
      - name: Deploy on Orphan Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: build
          force_orphan: true
